cc_moderator_forum_cp:
    pattern: /{_locale}/dashboard/moderator
    defaults: { _controller: CCDNComponentDashboardBundle:Dashboard:show, _locale: en }

#
# Post Moderation.
#
cc_moderator_forum_posts_show_all_locked:
    pattern: /{_locale}/moderate/forum/post/show/locked
    defaults: { _controller: CCDNForumModeratorBundle:Post:showLocked, _locale: en, page: 1 }

cc_moderator_forum_posts_show_all_locked_paginated:
    pattern: /{_locale}/moderate/forum/post/show/locked/page/{page}
    defaults: { _controller: CCDNForumModeratorBundle:Post:showLocked, _locale: en, page: 1 }
                
cc_moderator_forum_post_lock:
    pattern: /{_locale}/moderate/forum/post/{post_id}/lock
    defaults: { _controller: CCDNForumModeratorBundle:Post:lock, _locale: en }

cc_moderator_forum_post_unlock:
    pattern: /{_locale}/moderate/forum/post/{post_id}/unlock
    defaults: { _controller: CCDNForumModeratorBundle:Post:unlock, _locale: en }

cc_moderator_forum_post_restore:
    pattern: /{_locale}/moderate/forum/post/{post_id}/restore
    defaults: { _controller: CCDNForumModeratorBundle:Post:restore, _locale: en }

cc_moderator_forum_posts_bulk_action:
    pattern: /{_locale}/moderate/forum/post/locked/action/checked
    defaults: { _controller: CCDNForumModeratorBundle:Post:bulk, _locale: en }

#  
# Topic Moderation.
#
cc_moderator_forum_topics_closed_show_all:
    pattern: /{_locale}/moderate/forum/topic/show/closed
    defaults: { _controller: CCDNForumModeratorBundle:Topic:showClosed, _locale: en, page: 1 }

cc_moderator_forum_topics_closed_show_all_paginated:
    pattern: /{_locale}/moderate/forum/topic/show/closed/page/{page}
    defaults: { _controller: CCDNForumModeratorBundle:Topic:showClosed, _locale: en, page: 1 }
                        
cc_moderator_forum_topic_close:
    pattern: /{_locale}/moderate/forum/topic/{topic_id}/close
    defaults: { _controller: CCDNForumModeratorBundle:Topic:close, _locale: en }

cc_moderator_forum_topic_reopen:
    pattern: /{_locale}/moderate/forum/topic/{topic_id}/reopen
    defaults: { _controller: CCDNForumModeratorBundle:Topic:reopen, _locale: en }

cc_moderator_forum_topic_sticky:
    pattern: /{_locale}/moderate/forum/topic/{topic_id}/sticky
    defaults: { _controller: CCDNForumModeratorBundle:Topic:sticky, _locale: en }
    
cc_moderator_forum_topic_unsticky:
    pattern: /{_locale}/moderate/forum/topic/{topic_id}/unsticky
    defaults: { _controller: CCDNForumModeratorBundle:Topic:unsticky, _locale: en }
    
cc_moderator_forum_topic_delete:
    pattern: /{_locale}/moderate/forum/topic/{topic_id}/delete
    defaults: { _controller: CCDNForumModeratorBundle:Topic:delete, _locale: en }

cc_moderator_forum_topic_delete_confirmed:
    pattern: /{_locale}/moderate/forum/topic/{topic_id}/delete/confirm
    defaults: { _controller: CCDNForumModeratorBundle:Topic:deleteConfirmed, _locale: en }

cc_moderator_forum_topic_restore:
    pattern: /{_locale}/moderate/forum/topic/{topic_id}/restore
    defaults: { _controller: CCDNForumModeratorBundle:Topic:restore, _locale: en }
  
cc_moderator_forum_topic_change_board:
    pattern: /{_locale}/moderate/forum/topic/{topic_id}/change/board
    defaults: { _controller: CCDNForumModeratorBundle:Topic:move, _locale: en }

cc_moderator_forum_topics_closed_bulk_action:
    pattern: /{_locale}/moderate/forum/topic/closed/action/checked
    defaults: { _controller: CCDNForumModeratorBundle:Topic:bulk, _locale: en }
                         
#
# Flagged posts moderation.
#
cc_moderator_forum_flagged_show_all:
    pattern: /{_locale}/moderate/forum/flagged/show
    defaults: { _controller: CCDNForumModeratorBundle:Flag:showFlagged, _locale: en, page: 1, status: 0 }

cc_moderator_forum_flagged_show_all_paginated:
    pattern: /{_locale}/moderate/forum/flagged/show/page/{page}
    defaults: { _controller: CCDNForumModeratorBundle:Flag:showFlaggedPosts, _locale: en, page: 1, status: 0 }

cc_moderator_forum_flagged_show_all_status:
    pattern: /{_locale}/moderate/forum/flagged/show/with/status/{status}
    defaults: { _controller: CCDNForumModeratorBundle:Flag:showFlagged, _locale: en, page: 1, status: 0 }

cc_moderator_forum_flagged_show_all_status_paginated:
    pattern: /{_locale}/moderate/forum/flagged/show/with/status/{status}/page/{page}
    defaults: { _controller: CCDNForumModeratorBundle:Flag:showFlaggedPosts, _locale: en, page: 1, status: 0 }

cc_moderator_forum_flag_mark:
    pattern: /{_locale}/moderate/forum/flag/{flag_id}/mark
    defaults: { _controller: CCDNForumModeratorBundle:Flag:markFlag, _locale: en }

cc_moderator_forum_flag_show:
    pattern: /{_locale}/moderate/forum/flag/{flag_id}/show
    defaults: { _controller: CCDNForumModeratorBundle:Flag:showFlag, _locale: en }
    
cc_moderate_forum_flag_action_bulk:
    pattern: /{_locale}/moderate/forum/flagged/action/checked
    defaults: { _controller: CCDNForumModeratorBundle:Flag:bulk, _locale: en }
        
