#
# Post Moderation.
#
ccdn_forum_moderator_post_show_all_locked:
    pattern: /{_locale}/moderate/forum/post/show/locked
    defaults: { _controller: CCDNForumModeratorBundle:Post:showLocked, _locale: en, page: 1 }

ccdn_forum_moderator_post_show_all_locked_paginated:
    pattern: /{_locale}/moderate/forum/post/show/locked/page/{page}
    defaults: { _controller: CCDNForumModeratorBundle:Post:showLocked, _locale: en, page: 1 }

ccdn_forum_moderator_post_lock:
    pattern: /{_locale}/moderate/forum/post/{postId}/lock
    defaults: { _controller: CCDNForumModeratorBundle:Post:lock, _locale: en }

ccdn_forum_moderator_post_unlock:
    pattern: /{_locale}/moderate/forum/post/{postId}/unlock
    defaults: { _controller: CCDNForumModeratorBundle:Post:unlock, _locale: en }

ccdn_forum_moderator_post_restore:
    pattern: /{_locale}/moderate/forum/post/{postId}/restore
    defaults: { _controller: CCDNForumModeratorBundle:Post:restore, _locale: en }

ccdn_forum_moderator_post_bulk_action:
    pattern: /{_locale}/moderate/forum/post/locked/action/checked
    defaults: { _controller: CCDNForumModeratorBundle:Post:bulk, _locale: en }

#
# Topic Moderation.
#
ccdn_forum_moderator_topic_show_all_closed:
    pattern: /{_locale}/moderate/forum/topic/show/closed
    defaults: { _controller: CCDNForumModeratorBundle:Topic:showClosed, _locale: en, page: 1 }

ccdn_forum_moderator_topic_show_all_closed_paginated:
    pattern: /{_locale}/moderate/forum/topic/show/closed/page/{page}
    defaults: { _controller: CCDNForumModeratorBundle:Topic:showClosed, _locale: en, page: 1 }

ccdn_forum_moderator_topic_bulk_action_closed:
    pattern: /{_locale}/moderate/forum/topic/closed/action/checked
    defaults: { _controller: CCDNForumModeratorBundle:Topic:bulk, _locale: en }

ccdn_forum_moderator_topic_close:
    pattern: /{_locale}/moderate/forum/topic/{topicId}/close
    defaults: { _controller: CCDNForumModeratorBundle:Topic:close, _locale: en }

ccdn_forum_moderator_topic_reopen:
    pattern: /{_locale}/moderate/forum/topic/{topicId}/reopen
    defaults: { _controller: CCDNForumModeratorBundle:Topic:reopen, _locale: en }

ccdn_forum_moderator_topic_sticky:
    pattern: /{_locale}/moderate/forum/topic/{topicId}/sticky
    defaults: { _controller: CCDNForumModeratorBundle:Topic:sticky, _locale: en }

ccdn_forum_moderator_topic_unsticky:
    pattern: /{_locale}/moderate/forum/topic/{topicId}/unsticky
    defaults: { _controller: CCDNForumModeratorBundle:Topic:unsticky, _locale: en }

ccdn_forum_moderator_topic_delete:
    pattern: /{_locale}/moderate/forum/topic/{topicId}/delete
    defaults: { _controller: CCDNForumModeratorBundle:Topic:delete, _locale: en }

ccdn_forum_moderator_topic_delete_confirmed:
    pattern: /{_locale}/moderate/forum/topic/{topicId}/delete/confirm
    defaults: { _controller: CCDNForumModeratorBundle:Topic:deleteConfirmed, _locale: en }

ccdn_forum_moderator_topic_restore:
    pattern: /{_locale}/moderate/forum/topic/{topicId}/restore
    defaults: { _controller: CCDNForumModeratorBundle:Topic:restore, _locale: en }

ccdn_forum_moderator_topic_change_board:
    pattern: /{_locale}/moderate/forum/topic/{topicId}/change/board
    defaults: { _controller: CCDNForumModeratorBundle:Topic:move, _locale: en }

#
# Flagged posts moderation.
#
ccdn_forum_moderator_flagged_show_all:
    pattern: /{_locale}/moderate/forum/flagged/show
    defaults: { _controller: CCDNForumModeratorBundle:Flag:showFlagged, _locale: en, page: 1, status: 0 }

ccdn_forum_moderator_flagged_show_all_paginated:
    pattern: /{_locale}/moderate/forum/flagged/show/page/{page}
    defaults: { _controller: CCDNForumModeratorBundle:Flag:showFlaggedPosts, _locale: en, page: 1, status: 0 }

ccdn_forum_moderator_flagged_show_all_status:
    pattern: /{_locale}/moderate/forum/flagged/show/with/status/{status}
    defaults: { _controller: CCDNForumModeratorBundle:Flag:showFlagged, _locale: en, page: 1, status: 0 }

ccdn_forum_moderator_flagged_show_all_status_paginated:
    pattern: /{_locale}/moderate/forum/flagged/show/with/status/{status}/page/{page}
    defaults: { _controller: CCDNForumModeratorBundle:Flag:showFlaggedPosts, _locale: en, page: 1, status: 0 }

ccdn_forum_moderator_update_flag:
    pattern: /{_locale}/moderate/forum/flag/{flagId}/update
    defaults: { _controller: CCDNForumModeratorBundle:Flag:updateFlag, _locale: en }

ccdn_forum_moderator_flag_show:
    pattern: /{_locale}/moderate/forum/flag/{flagId}/show
    defaults: { _controller: CCDNForumModeratorBundle:Flag:showFlag, _locale: en }

ccdn_forum_moderator_flag_bulk_action:
    pattern: /{_locale}/moderate/forum/flagged/action/checked
    defaults: { _controller: CCDNForumModeratorBundle:Flag:bulk, _locale: en }
