parameters:

    ccdn_forum_moderator.topic.manager.class:                     CCDNForum\ModeratorBundle\Manager\TopicManager
    ccdn_forum_moderator.post.manager.class:                      CCDNForum\ModeratorBundle\Manager\PostManager
    ccdn_forum_moderator.flag.manager.class:                      CCDNForum\ModeratorBundle\Manager\FlagManager

    ccdn_forum_moderator.flag.form.update.type.class:             CCDNForum\ModeratorBundle\Form\Type\FlagUpdateType
    ccdn_forum_moderator.flag.form.update.handler.class:          CCDNForum\ModeratorBundle\Form\Handler\FlagUpdateFormHandler

    ccdn_forum_moderator.topic.form.change_board.type.class:      CCDNForum\ModeratorBundle\Form\Type\TopicChangeBoardType
    ccdn_forum_moderator.topic.form.change_board.handler.class:   CCDNForum\ModeratorBundle\Form\Handler\TopicChangeBoardFormHandler

    ccdn_forum_moderator.dashboard.integrator.class:              CCDNForum\ModeratorBundle\Component\Dashboard\DashboardIntegrator

services:

    #
    # Managers.
    #
    ccdn_forum_moderator.topic.manager:
        class: %ccdn_forum_moderator.topic.manager.class%
        arguments:  [@doctrine, @service_container]
    ccdn_forum_moderator.post.manager:
        class: %ccdn_forum_moderator.post.manager.class%
        arguments:  [@doctrine, @service_container]
    ccdn_forum_moderator.flag.manager:
        class: %ccdn_forum_moderator.flag.manager.class%
        arguments:  [@doctrine, @service_container]

    #
    # Flag Forms.
    #
    ccdn_forum_moderator.flag.form.update.type:
        class:  %ccdn_forum_moderator.flag.form.update.type.class%
        arguments:  [@doctrine]
    ccdn_forum_moderator.flag.form.update.handler:
        class:  %ccdn_forum_moderator.flag.form.update.handler.class%
        arguments:  [@form.factory, @service_container, @ccdn_forum_moderator.flag.manager]

    #
    # Topic Forms.
    #
    ccdn_forum_moderator.topic.form.change_board.type:
        class:  %ccdn_forum_moderator.topic.form.change_board.type.class%
        arguments:  [@doctrine]
    ccdn_forum_moderator.topic.form.change_board.handler:
        class:  %ccdn_forum_moderator.topic.form.change_board.handler.class%
        arguments:  [@form.factory, @service_container, @ccdn_forum_moderator.topic.manager]

    #
    # Dashboard Integrator.
    #
    ccdn_forum_moderator.dashboard.integrator:
        class: %ccdn_forum_moderator.dashboard.integrator.class%
        arguments: [@service_container]
        tags:
            - { name: ccdn_component_dashboard.integrator }
