CCDNForum\ForumBundle\Entity\Flag:
    properties:
        status:
            - NotNull: { groups: [moderate] }
        moderatorsNote:
            - Type: { type: string, groups: [moderate] }
            - NotBlank: { groups: [moderate] }
            - MinLength: { limit: 5, groups: [moderate] }
            - MaxLength: { limit: 2000, groups: [moderate] }
